n = 12
(
    GET_LANG,
    GET_NAME,
    GET_CONTACT,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    GET_PROMOCODE,
    GET_REGION,
    GET_ADDRESS,
    GET_PHOTO,
) = range(0, n)